### ISSUE TITLE
建議添加Tag來歸檔到release中

### ISSUE THREAD

**Issue by duduluu** [Ludeon/RimWorld-ChineseTraditional#1]
翻譯進入A17了，遊戲版本還是A16，導致好多人從這裡下載之後翻譯不匹配。
在release中添加個A16歸檔，在readme中寫上注意事項，儘量避免發生這類事情（雖然還是好多人不看注意事項直接下載……）。

**Comment by nimula** [comment]
目前翻譯進行到1.0，但是遊戲版本是A18。直接下載同樣會造成下載後翻譯不匹配的問題。
建議將1.0的翻譯移至branch上進行。讓對git沒經驗的玩家能夠順利使用中文化。
再次感謝 Ludeon 對中文化的貢獻 謝謝
