### ISSUE TITLE
一般討論 offset的意思

### ISSUE THREAD

**Issue by SCThunder** [Ludeon/RimWorld-ChineseTraditional#196]
offset目前是偏移
就用處而言，是把數值強行加減(相對multiplier倍率，是把數值x0.3之類)

**Comment by Darkborderman** [comment]
覺得幾個很像的字詞可以一起比較, 下面我放偏好的翻譯優先序

| name | trans. |
| --- | --- |
| offset | 補正 , 偏移 |
| factor |  倍率, 加乘 |
| multiplier | 倍率, 加乘 |
