### ISSUE TITLE
Translation data for language Traditional Chinese has 241 errors. Generate translation report for more info.

### ISSUE THREAD

**Issue by NBurger500** [Ludeon/RimWorld-ChineseTraditional#226]
如標題
生成翻譯報告可以看到很多錯誤

**Comment by SCThunder** [comment]
![image](https://github.com/Ludeon/RimWorld-ChineseTraditional/assets/12846908/a779bd63-5ee8-4126-805b-ca1f7ccbc4ad)
都是一些UNUSED的多餘行而已，舉例圖中這個已被取代了
這些我們不會碰，因為是原作那邊更改variable造成的，他們哪天就會自己刪掉
