### ISSUE TITLE
翻譯問題

### ISSUE THREAD

**Issue by NBurger500** [Ludeon/RimWorld-ChineseTraditional#227]
## 檔案名稱

Ideology/DefInjected/QuestScriptDef
/Script_ReliquaryPilgrims.xml
## 問題部份

29行
<li>andFollowers(pilgrimCount==2)-和另一位[faction_pawnSingular]</li>
## 修正

<li>andFollowers(pilgrimCount==2)->和另一位[faction_pawnSingular]</li>
少了箭頭，每次來朝聖者都會跳紅字

**Comment by SCThunder** [comment]
已修正，感謝

**Comment by NBurger500** [comment]
@SCThunder 
Biotech/DefInjected/InteractionDef/Interactions_Social.xml

117行  <li>animal_verb-馴服</li>
這裡也少了箭頭
<li>animal_verb->馴服</li>

**Comment by SCThunder** [comment]
> @SCThunder Biotech/DefInjected/InteractionDef/Interactions_Social.xml
> 
> 117行
> 
> * animal_verb-馴服
> 
> 這裡也少了箭頭
> * animal_verb->馴服

也修正了，感謝

**Comment by NBurger500** [comment]
@SCThunder Ideology/DefInjected/QuestScriptDef/Script_WorkSite.xml

33行之後沒翻譯到

**Comment by SCThunder** [comment]
> @SCThunder Ideology/DefInjected/QuestScriptDef/Script_WorkSite.xml
> 
> 33行之後沒翻譯到

那是因為中文沒英文那麼多同義詞，考慮到通順和美觀而不強行翻譯。

**Comment by NBurger500** [comment]
問題是那是一個腳本，生成的時候沒對應的地方會出紅字

**Comment by SCThunder** [comment]
> 問題是那是一個腳本，生成的時候沒對應的地方會出紅字

方便上載一下紅字的截圖嗎?
這種<li></li>格式的文字應該是可以隨意加減的

**Comment by NBurger500** [comment]
![image](https://github.com/Ludeon/RimWorld-ChineseTraditional/assets/81086205/387ad191-12c4-4a0e-b28a-c15f1db7eb3c)
![image](https://github.com/Ludeon/RimWorld-ChineseTraditional/assets/81086205/029db0cb-5e3d-4c58-8661-2996f960001e)
![image](https://github.com/Ludeon/RimWorld-ChineseTraditional/assets/81086205/c3f08642-2e94-4d2b-8d70-79b785e6a989)
![image](https://github.com/Ludeon/RimWorld-ChineseTraditional/assets/81086205/c1bfaf3a-8d92-4fe9-bc84-0ca35ca55c3c)
![image](https://github.com/Ludeon/RimWorld-ChineseTraditional/assets/81086205/1cb94fb9-56eb-4e82-820b-07b2eb16a70b)

**Comment by NBurger500** [comment]
剛剛測試了好幾次應該是mod的問題沒錯了 :(

**Comment by Darkborderman** [comment]
如果是 mod 的問題那 issue 我就先 closed 了, 抱歉現在才發現到被 assign
