### ISSUE TITLE
嬰兒說話

### ISSUE THREAD

**Issue by stanson318** [Ludeon/RimWorld-ChineseTraditional#228]
## 檔案名稱
不清楚

## 問題部份
英文版嬰兒的說話(白字部份)是嬰兒語, 很有趣
繁中兩行都是一樣的文字, 灰字的部份重覆了 而且顯得 [翻譯:] 這個部份多餘了

## 修正
將白色的部份改成 哇哇嗚嗚咕咕嚕 之類的

**Comment by Darkborderman** [comment]
Sorry 這裡現在才看到 我問問翻譯組大家的意見

**Comment by SCThunder** [comment]
這是系統無法辨認中文的問題。原本gugugaga是從本意的英語中生成的，但現在本意是中文時，系統則會錯亂而把「翻譯」後的本意直接寫出來。已經向製作組方面提出過但沒解決
