### ISSUE TITLE
身體部件翻譯

### ISSUE THREAD

**Issue by shiuanyue** [Ludeon/RimWorld-ChineseTraditional#3]
我是最近才進會員不太懂這邊的機制
進主題
我利用一款字碼轉換器 針對重複性高的單字來做快速翻譯
希望翻譯組可以聯絡我

**Comment by kerong08ng** [comment]
新發佈的B19 好像這邊也還沒有更新最新的文檔。
剛剛試用過遊戲內建的『翻譯報告』(Translation Report)功能，也發現了TaleDef，RulePackDef等新增的文檔尚未翻譯，為數二三千項。
所以我想知道現有譯者的進度，看看有什麼可以幫得上忙
